[phases.setup]
nixPkgs = ["python311", "nodejs_18", "gcc", "libpq-dev", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements-railway.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python main.py" 