[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql_16.dev"]

[phases.install]
cmds = [
  "cd backend",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python start.py"

[variables]
PYTHONPATH = "/app/backend" 