[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql_16.dev", "curl"]

[phases.install]
cmds = [
  "cd backend",
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python start.py"

[variables]
PYTHONPATH = "/app/backend" 