[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements-railway.txt"
]

[start]
cmd = "cd backend && python main.py" 