[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

[[services]]
name = "afteride-backend"
source = "backend"
buildCommand = "pip install -r requirements-railway.txt"
startCommand = "python main.py"
variables = [
  "ENVIRONMENT=production",
  "DEBUG=false",
  "LOG_LEVEL=INFO"
]

[[services]]
name = "afteride-frontend"
source = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npx serve -s dist -l $PORT"
variables = [
  "NODE_ENV=production",
  "VITE_API_URL=${RAILWAY_STATIC_URL_AFTERIDE_BACKEND}/api/v1"
]

[[services]]
name = "postgres"
image = "postgres:15-alpine"
variables = [
  "POSTGRES_DB=afteride",
  "POSTGRES_USER=postgres",
  "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
]

[[services]]
name = "redis"
image = "redis:7-alpine" 