[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

[[services]]
name = "postgres"
image = "postgres:15-alpine"
variables = [
  "POSTGRES_DB=afteride",
  "POSTGRES_USER=postgres",
  "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
]

[[services]]
name = "redis"
image = "redis:7-alpine" 