[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

[[services]]
name = "afteride-backend"
source = "backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "afteride-frontend"
source = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npx serve -s dist -l $PORT"

[[services]]
name = "postgres"
image = "postgres:15-alpine"
variables = [
  "POSTGRES_DB=afteride",
  "POSTGRES_USER=postgres",
  "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
]

[[services]]
name = "redis"
image = "redis:7-alpine" 