[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql_16.dev", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python start.py"

[variables]
PYTHONPATH = "/app" 