[phases.setup]
nixPkgs = ["python311", "gcc", "libpq-dev", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "python install_dependencies.py"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd backend && python main.py" 