[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1

[variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
PYTHONPATH = "/app"
PORT = "8000" 